name: Bug 反馈
description: "提交项目 Bug 报告"
title: "[Bug] "
labels: ["bug"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: 前置确认
      description: 在提交之前，请勾选以下选项以确认您已完成必要的自助排查
      options:
        - label: 我确认这是项目 **Bug**， 而非操作不当或使用不清楚。否则请使用其他 Issue 模板或移步[讨论区](https://github.com/nelvko/clash-for-linux-install/discussions)
          required: true
        - label: 我已查阅 [常见问题](https://github.com/nelvko/clash-for-linux-install/wiki/FAQ)，但仍未找到解决方案
          required: true
        - label: 我已使用关键字查询相关 [Issues](https://github.com/nelvko/clash-for-linux-install/issues?q=is%3Aissue)，但仍未找到解决方案
          required: true
        - label: 我已确认本地与远程仓库最新提交的哈希一致。 (`git rev-parse --short HEAD`)
          required: true

  - type: input
    id: branch
    attributes:
      label: 使用的分支
      placeholder: master / ...
    validations:
      required: true

  - type: input
    id: commit_id
    attributes:
      label: Commit ID
      description: |
        请提供当前 Commit 哈希：`git rev-parse --short HEAD`
    validations:
      required: true

  - type: input
    id: shell
    attributes:
      label: Shell 环境
      placeholder: bash / zsh / ...
    validations:
      required: true

  - type: textarea
    id: system
    attributes:
      label: 系统信息
      description: |
        请提供系统相关信息，可任选以下命令输出之一：
        ```bash
        hostnamectl
        lsb_release -a
        uname -a
        ```
      render: shell
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: 描述 & 复现
      description: |
        请详细描述：
        1. 操作步骤  
        2. 期望结果  
        3. 实际表现  
        4. ~~必要时~~最好附上截图
        **请勿泄露订阅、IP 等敏感信息**
      # placeholder: |

    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: 请提供相关日志输出或截图
      render: shell
